# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 00:19

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
