# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boo',
            old_name='datebood',
            new_name='date',
        ),
    ]
