# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0002_auto_20160915_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='tags',
            field=models.ManyToManyField(to='halloween.Tag'),
        ),
    ]
