# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0002_costume_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nope', models.IntegerField()),
            ],
        ),
    ]
