# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0003_nope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boo',
            name='costume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boos', to='halloween.Costume'),
        ),
        migrations.AlterField(
            model_name='boo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boos', to=settings.AUTH_USER_MODEL),
        ),
    ]
