# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halloween', '0003_costume_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='boo',
            name='costume',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='boos', to='halloween.Costume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boo',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='boos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costumeelement',
            name='costume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costume_elements', to='halloween.Costume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costumeelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costume_elements', to='halloween.Element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costumeelement',
            name='tags',
            field=models.ManyToManyField(to='halloween.Tag'),
        ),
    ]
