# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0004_auto_20161002_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('costume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='halloween.Costume')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='halloween.Element')),
            ],
        ),
        migrations.RemoveField(
            model_name='costumeelement',
            name='costume',
        ),
        migrations.RemoveField(
            model_name='costumeelement',
            name='element',
        ),
        migrations.DeleteModel(
            name='Nope',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='costumeelements',
        ),
        migrations.DeleteModel(
            name='CostumeElement',
        ),
        migrations.AddField(
            model_name='tag',
            name='supplies',
            field=models.ManyToManyField(blank=True, related_name='tags', to='halloween.Supply'),
        ),
    ]
