# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halloween', '0005_auto_20161002_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to=settings.AUTH_USER_MODEL),
        ),
    ]
