# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0005_auto_20160915_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='tags',
        ),
        migrations.AddField(
            model_name='costume',
            name='tags',
            field=models.ManyToManyField(to='halloween.Tag'),
        ),
    ]
