# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0008_auto_20160915_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='tags',
        ),
        migrations.AddField(
            model_name='costume',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costumes', to='halloween.Tag'),
        ),
    ]
