# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0011_auto_20160915_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='costume',
            new_name='costumes',
        ),
    ]
