# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0012_auto_20160915_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='costume_elements',
        ),
        migrations.AddField(
            model_name='tag',
            name='costume_elements',
            field=models.ManyToManyField(related_name='tags', to='halloween.CostumeElement'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='costumes',
        ),
        migrations.AddField(
            model_name='tag',
            name='costumes',
            field=models.ManyToManyField(related_name='tags', to='halloween.Costume'),
        ),
    ]
