# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0014_auto_20160915_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='costumes',
        ),
        migrations.AddField(
            model_name='tag',
            name='costumes',
            field=models.ManyToManyField(related_name='tags', to='halloween.Costume'),
        ),
    ]
