# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0015_auto_20160915_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumeElementTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumeelement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='halloween.CostumeElement')),
            ],
        ),
        migrations.CreateModel(
            name='CostumeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='halloween.Costume')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='costume_elements',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='costumes',
        ),
        migrations.AlterField(
            model_name='boo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='costumetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumes', to='halloween.Tag'),
        ),
        migrations.AddField(
            model_name='costumeelementtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='halloween.Tag'),
        ),
    ]
