# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0016_auto_20160915_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumetag',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
