# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0017_costumetag_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumetag',
            name='date',
        ),
    ]
