# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0018_remove_costumetag_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumeelementtag',
            name='costumeelement',
        ),
        migrations.RemoveField(
            model_name='costumeelementtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='costumetag',
            name='costume',
        ),
        migrations.RemoveField(
            model_name='costumetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='boo',
            name='date',
        ),
        migrations.AddField(
            model_name='tag',
            name='costumeelements',
            field=models.ManyToManyField(to='halloween.CostumeElement'),
        ),
        migrations.AddField(
            model_name='tag',
            name='costumes',
            field=models.ManyToManyField(to='halloween.Costume'),
        ),
        migrations.DeleteModel(
            name='CostumeElementTag',
        ),
        migrations.DeleteModel(
            name='CostumeTag',
        ),
    ]
