# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0019_auto_20160915_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='costumeelements',
            field=models.ManyToManyField(blank=True, related_name='tags', to='halloween.CostumeElement'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='costumes',
            field=models.ManyToManyField(blank=True, related_name='tags', to='halloween.Costume'),
        ),
    ]
