# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0020_auto_20160915_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boo',
            old_name='user',
            new_name='owner',
        ),
    ]
