# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0022_auto_20160919_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumeelement',
            name='name',
            field=models.CharField(default='temp', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costume',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='costumes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
