# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0023_auto_20160919_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeelement',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
