# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0024_auto_20160919_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeelement',
            name='costume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costume_elements', to='halloween.Costume'),
        ),
    ]
