# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0026_auto_20160920_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='datecreated',
        ),
    ]
