# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halloween', '0028_auto_20160922_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeelement',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costumeelements', to='halloween.Element'),
        ),
    ]
